package uni.gaben.iscat.universe.entity.brain;

import org.dyn4j.collision.Filter;
import org.dyn4j.dynamics.Body;
import org.dyn4j.dynamics.BodyFixture;
import org.dyn4j.geometry.AABB;
import org.dyn4j.geometry.Vector2;
import org.dyn4j.world.DetectFilter;
import org.dyn4j.world.result.DetectResult;
import uni.gaben.iscat.universe.UniverseModel;
import uni.gaben.iscat.universe.entity.brain.targets.CachedNeighboursTarget;
import uni.gaben.iscat.universe.entity.AbstractEntityModel;
import uni.gaben.iscat.universe.entity.player.PlayerModel;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.function.Function;
import java.util.function.Predicate;

@FunctionalInterface
public interface Target {

    /** Returns all entities associated with this target (empty if targeting a point in space). */
    List<AbstractEntityModel> getEntities(UniverseModel universe);

    /** Returns the positions of all relevant entities or points. */
    default List<Vector2> getPositions(UniverseModel universe) {
        List<AbstractEntityModel> entities = getEntities(universe);
        // Pre-size the ArrayList to avoid array resizing overhead
        List<Vector2> positions = new ArrayList<>(entities.size());

        // Use indexed for-loop to avoid Iterator allocations generated by for-each loops
        for (int i = 0; i < entities.size(); i++) {
            AbstractEntityModel e = entities.get(i);
            if (!e.shouldRemove()) {
                positions.add(e.getTransform().getTranslation());
            }
        }
        return positions;
    }

    /** Returns a single representative position (the exact point, or the center of a group). */
    default Vector2 getPosition(UniverseModel universe) {
        List<AbstractEntityModel> entities = getEntities(universe);
        if (entities.isEmpty()) return null;

        double sumX = 0.0;
        double sumY = 0.0;
        int count = 0;

        // Bypass getPositions() entirely. Compute the average directly to avoid building a List<Vector2>
        for (int i = 0; i < entities.size(); i++) {
            AbstractEntityModel e = entities.get(i);
            if (!e.shouldRemove()) {
                Vector2 pos = e.getTransform().getTranslation();
                sumX += pos.x;
                sumY += pos.y;
                count++;
            }
        }

        if (count == 0) return null;
        if (count == 1) return new Vector2(sumX, sumY);

        return new Vector2(sumX / count, sumY / count);
    }

    // ── Factories ────────────────────────────────────────────────────────

    static Target ofPoint(Vector2 point) {
        // Cache the point and the singleton list ONCE at instantiation
        final Vector2 copiedPoint = point.copy();
        final List<Vector2> cachedList = Collections.singletonList(copiedPoint);

        return new Target() {
            @Override
            public List<AbstractEntityModel> getEntities(UniverseModel universe) { return Collections.emptyList(); }

            @Override
            public List<Vector2> getPositions(UniverseModel universe) { return cachedList; } // Zero GC

            @Override
            public Vector2 getPosition(UniverseModel universe) { return copiedPoint; } // Zero GC
        };
    }

    static Target ofDynamicPoint(Function<UniverseModel, Vector2> query) {
        return new Target() {
            @Override
            public List<AbstractEntityModel> getEntities(UniverseModel universe) { return Collections.emptyList(); }

            @Override
            public List<Vector2> getPositions(UniverseModel universe) {
                Vector2 p = query.apply(universe);
                return p == null ? Collections.emptyList() : Collections.singletonList(p);
            }

            @Override
            public Vector2 getPosition(UniverseModel universe) {
                return query.apply(universe); // Direct return, bypasses intermediate lists
            }
        };
    }

    static Target ofEntity(AbstractEntityModel entity) {
        return world -> entity.shouldRemove() ? Collections.emptyList() : Collections.singletonList(entity);
    }

    static Target ofPlayer() {
        return universe -> {
            PlayerModel p = universe.getPlayer();
            return (p != null && !p.shouldRemove()) ? Collections.singletonList(p) : Collections.emptyList();
        };
    }

    static Target ofEntities(Function<UniverseModel, List<AbstractEntityModel>> query) {
        return query::apply;
    }

    /**
     * Returns a Target that queries neighbours using a dynamic AABB (re‑computed every call).
     * To avoid repeated queries, use neighboursCached() instead.
     */
    static Target neighbours(Body body, double range, DetectFilter<Body, BodyFixture> filter) {
        return universe -> {
            AABB aabb = body.createAABB();
            AABB detectionBox = new AABB(
                    aabb.getMinX() - range,
                    aabb.getMinY() - range,
                    aabb.getMaxX() + range,
                    aabb.getMaxY() + range
            );

            List<DetectResult<Body, BodyFixture>> detected = universe.detect(detectionBox, filter);
            List<AbstractEntityModel> result = new ArrayList<>(detected.size());

            for (int i = 0; i < detected.size(); i++) {
                result.add((AbstractEntityModel) detected.get(i).getBody());
            }

            return result;
        };
    }

    static Target neighboursCached(Body self, double range,
                                   boolean ignoreSensors, boolean ignoreDisabled,
                                   Filter categoryMaskFilter,
                                   UniverseFilter universeFilter,
                                   Predicate<Body> bodyPredicate) {
        UniverseDetectFilter filter = new UniverseDetectFilter(
                ignoreSensors, ignoreDisabled, categoryMaskFilter, universeFilter, bodyPredicate);
        return new CachedNeighboursTarget(self, range, filter);
    }

    // Even simpler: only body predicate, no universe filter
    static Target neighboursCached(Body self, double range, Predicate<Body> bodyPredicate) {
        return neighboursCached(self, range, true, true, null, null, bodyPredicate);
    }

    /**
     * Returns a new Target that filters the entities of this target.
     * The underlying list is still cached; filtering is applied on each call.
     */
    default Target filtered(Predicate<AbstractEntityModel> predicate) {
        return world -> {
            List<AbstractEntityModel> all = getEntities(world);
            List<AbstractEntityModel> filtered = new ArrayList<>(all.size()); // Pre-size safely

            for (int i = 0; i < all.size(); i++) {
                AbstractEntityModel e = all.get(i);
                if (predicate.test(e)) {
                    filtered.add(e);
                }
            }
            return filtered;
        };
    }
}